### ISSUE TITLE
version of jaguar this package depends on is too old

### ISSUE THREAD

**Issue by ghost** [Jaguar-dart/jaguar_flutter_asset#1]
See the pubspec for https://github.com/jaguar-examples/flutter_webview

You will see that jaguar_flutter_asset is depending on a version of jaguar of ^1.1.5, but and flutter_webview depends on jaguar ^2.0.2, so the flutter webview fails.

Can you upgrade jaguar_flutter_assetto use jaguar ^2.0.2 ?

**Comment by tejainece** [comment]
Fixed by https://github.com/Jaguar-dart/jaguar_flutter_asset/commit/331afe2460655c3d1051ef2d6823b03018a47902

Let me know if this fixed your problem.

Thanks.

**Comment by ghost** [comment]
thanks @tejainece , all good now :)
