### ISSUE TITLE
Help on custom asset path

### ISSUE THREAD

**Issue by allandaleho** [Jaguar-dart/jaguar_flutter_asset#2]
Can anyone give an example how to call a custom path, I tried the following :
`server.addRoute(serveFlutterAssets(path: '/assets/pages/tou/'));`
I've tried other combinations as well but can't seem to understand how path is resolved in code.

Hope anyone can help!

**Comment by tejainece** [comment]
Did you find it out?

**Comment by ghost** [comment]
use `prefix` instead, it's realtive to the assets folder
```
server.addRoute(serveFlutterAssets(prefix: 'pages/tou/'));
```
With that, it will serve the folder `/assets/pages/tou`,
