### ISSUE TITLE
Can't able to run in iOS

### ISSUE THREAD

**Issue by shariful2011** [Jaguar-dart/jaguar_flutter_asset#3]
Does this compatible with iOS? I can't run it in iOS.

**Comment by tejainece** [comment]
It is compatible. What error do you get?

**Comment by shariful2011** [comment]
After I click on the floating button I got this error:
Launching lib/main.dart on iPhone XR in debug mode...
Xcode build done.                                           30.5s
Lost connection to device.
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001036d41bb __exceptionPreprocess + 331
	1   libobjc.A.dylib                     0x0000000102c72735 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001036f2f44 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00000001036d8ed6 ___forwarding___ + 1446
	4   CoreFoundation                      0x00000001036dada8 _CF_forwarding_prep_0 + 120
	5   flutter_webview_plugin              0x000000010262ba8c -[FlutterWebviewPlugin initWebview:] + 1692
	6   flutter_webview_plugin              0x000000010262adce -[FlutterWebviewPlugin handleMethodCall:result:] + 254
	7   Flutter                             0x0000000100e9b5fa __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 115
	8   Flutter  <…>
Exited (sigterm)

Simulator closed with this message.

**Comment by tejainece** [comment]
The problem is probably with FlutterWebviewPlugin not Jaguar. Did you try to just access the API using http client?

**Comment by shariful2011** [comment]
Also with webview_flutter it's not showing anything. This is what I did:
body: WebView(
        initialUrl: 'http://localhost:8080/html_files/about this app.html',
        onWebViewCreated: (WebViewController webViewController) {
          _controller.complete(webViewController); 
        },
      )

In Android, the HTML page is showing in the webview but in iOS blank.

I am testing the sample flutter_webview. In Android, it's working but in iOS getting that error.

**Comment by tejainece** [comment]
Can you try with `127.0.0.1` as hostname instead of localhost.

**Comment by shariful2011** [comment]
WIth 127.0.0.1 is working, thanks for your time.

**Comment by tejainece** [comment]
I have fixed the README.
